"""定义训练上下文使用的目录、文件和工作流常量。"""

WORKFLOW_TYPE_TRAINING = "training"

TRAINING_DATA_DIRNAME = "training"
TRAINING_OUTPUTS_DIRNAME = "training_outputs"
TRAINING_CALIBRATIONS_DIRNAME = "training_calibrations"
TRAINING_TASK_RUNS_DIRNAME = "task_runs"
TRAINING_WEIGHTS_DIRNAME = "weights"
TRAINING_EXPORT_DIRNAME = "export"
TRAINING_INFERENCE_DIRNAME = "inference"

TRAINING_CONFIG_FILENAME = "training_config.json"
TRAINING_WEIGHT_BEST_FILENAME = "best.pt"
TRAINING_WEIGHT_LAST_FILENAME = "last.pt"
TRAINING_WEIGHT_FILENAMES = (
    TRAINING_WEIGHT_BEST_FILENAME,
    TRAINING_WEIGHT_LAST_FILENAME,
)
