"""跨上下文共享的视觉任务类型协议。"""

VISION_TASK_TYPE_DETECT = "detect"
VISION_TASK_TYPE_CLASSIFY = "classify"
VISION_TASK_TYPE_SEGMENT = "segment"
VISION_TASK_TYPE_POSE = "pose"

VISION_TASK_TYPES = (
    VISION_TASK_TYPE_DETECT,
    VISION_TASK_TYPE_CLASSIFY,
    VISION_TASK_TYPE_SEGMENT,
    VISION_TASK_TYPE_POSE,
)
VISION_TASK_TYPE_SET = frozenset(VISION_TASK_TYPES)
